/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ramos_lopez_javierdi;

import java.util.Locale;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;
import org.netbeans.validation.api.builtin.stringvalidation.MayusculaValidator;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author javie
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        fourtbutton.setEnabled(false);
        setLocationRelativeTo(null);
        setTitle("FORMULARIO DE COMPRA");
        ValidationGroup group = validationPanel1.getValidationGroup();
        
        group.add(primerTextField,new MayusculaValidator());
        group.add(segundoTextField,new MayusculaValidator());
        group.add(tercerTextField, StringValidators.maxLength(9), StringValidators.minLength(9),StringValidators.REQUIRE_NON_NEGATIVE_NUMBER);
        group.add(cuartoTextField, StringValidators.REQUIRE_NON_EMPTY_STRING,StringValidators.REQUIRE_VALID_INTEGER,StringValidators.maxLength(8),StringValidators.minLength(8));
        group.add(quintoTextField, StringValidators.REQUIRE_NON_EMPTY_STRING,StringValidators.minLength(3),StringValidators.maxLength(3));
        
        validationPanel1.addChangeListener( new ChangeListener(){
            @Override
            public void stateChanged(ChangeEvent e) {
                
                if(validationPanel1.getProblem() == null){
                    
                    fourtbutton.setEnabled(true);
                    
                }else{
                    
                    fourtbutton.setEnabled(false);
                    
                }
                
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstPanel = new javax.swing.JPanel();
        secondPaneñ = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        thirdPanel = new javax.swing.JPanel();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        fifthPanel = new javax.swing.JPanel();
        primerTexto = new javax.swing.JLabel();
        primerTextField = new javax.swing.JTextField();
        segundoTexto = new javax.swing.JLabel();
        segundoTextField = new javax.swing.JTextField();
        tercerTexto = new javax.swing.JLabel();
        tercerTextField = new javax.swing.JTextField();
        cuartoTexto = new javax.swing.JLabel();
        cuartoTextField = new javax.swing.JTextField();
        quintoTexto = new javax.swing.JLabel();
        quintoTextField = new javax.swing.JTextField();
        fourthPanel = new javax.swing.JPanel();
        fourtbutton = new javax.swing.JButton();
        fourthutton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstPanel.setBackground(new java.awt.Color(255, 255, 0));

        secondPaneñ.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Source Code Pro Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("FORMULARIO");
        secondPaneñ.add(jLabel1);
        secondPaneñ.add(jLabel2);

        thirdPanel.setBackground(new java.awt.Color(255, 255, 0));

        validationPanel1.setBackground(new java.awt.Color(255, 255, 0));

        fifthPanel.setBackground(new java.awt.Color(255, 255, 0));
        fifthPanel.setLayout(new java.awt.GridLayout(5, 2));

        primerTexto.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        primerTexto.setForeground(new java.awt.Color(0, 0, 102));
        primerTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primerTexto.setText("Nombre ");
        fifthPanel.add(primerTexto);

        primerTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerTextFieldActionPerformed(evt);
            }
        });
        fifthPanel.add(primerTextField);

        segundoTexto.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        segundoTexto.setForeground(new java.awt.Color(0, 0, 102));
        segundoTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segundoTexto.setText("Apellidos  ");
        fifthPanel.add(segundoTexto);

        segundoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fifthPanel.add(segundoTextField);

        tercerTexto.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        tercerTexto.setForeground(new java.awt.Color(0, 0, 102));
        tercerTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tercerTexto.setText("DNI ");
        fifthPanel.add(tercerTexto);

        tercerTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fifthPanel.add(tercerTextField);

        cuartoTexto.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        cuartoTexto.setForeground(new java.awt.Color(0, 0, 102));
        cuartoTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuartoTexto.setText("Número de cuenta ");
        fifthPanel.add(cuartoTexto);

        cuartoTextField.setForeground(new java.awt.Color(0, 0, 102));
        cuartoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fifthPanel.add(cuartoTextField);

        quintoTexto.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        quintoTexto.setForeground(new java.awt.Color(0, 0, 102));
        quintoTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quintoTexto.setText("CVV  ");
        fifthPanel.add(quintoTexto);

        quintoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fifthPanel.add(quintoTextField);

        javax.swing.GroupLayout thirdPanelLayout = new javax.swing.GroupLayout(thirdPanel);
        thirdPanel.setLayout(thirdPanelLayout);
        thirdPanelLayout.setHorizontalGroup(
            thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thirdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fifthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(thirdPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        thirdPanelLayout.setVerticalGroup(
            thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fifthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        fourthPanel.setBackground(new java.awt.Color(255, 255, 0));

        fourtbutton.setBackground(new java.awt.Color(51, 255, 0));
        fourtbutton.setFont(new java.awt.Font("Source Code Pro Black", 1, 36)); // NOI18N
        fourtbutton.setForeground(new java.awt.Color(0, 0, 102));
        fourtbutton.setText("ENVIAR");
        fourtbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourtbuttonActionPerformed(evt);
            }
        });
        fourthPanel.add(fourtbutton);

        fourthutton1.setBackground(new java.awt.Color(51, 255, 0));
        fourthutton1.setFont(new java.awt.Font("Source Code Pro Black", 1, 36)); // NOI18N
        fourthutton1.setForeground(new java.awt.Color(0, 0, 102));
        fourthutton1.setText("VOLVER");
        fourthutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthutton1ActionPerformed(evt);
            }
        });
        fourthPanel.add(fourthutton1);

        javax.swing.GroupLayout firstPanelLayout = new javax.swing.GroupLayout(firstPanel);
        firstPanel.setLayout(firstPanelLayout);
        firstPanelLayout.setHorizontalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fourthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thirdPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secondPaneñ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        firstPanelLayout.setVerticalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secondPaneñ, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thirdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fourthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que contiene el botón de nos llevará a una página donde se vea un mensaje tras haber realizado la compra
     * @param evt 
     */
    private void fourtbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourtbuttonActionPerformed
        
        
        Vendido v = new Vendido(this,true);
        this.setVisible(false);
        v.setVisible(true);

        
    }//GEN-LAST:event_fourtbuttonActionPerformed

    /**
     * Método que contendrá el botón de volver, y volverá un paso atrás
     * @param evt 
     */
    private void fourthutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthutton1ActionPerformed

        VentanaPrincipal vp = new VentanaPrincipal();
        
        this.setVisible(false);
        vp.setVisible(true);
    }//GEN-LAST:event_fourthutton1ActionPerformed

    private void primerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primerTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Locale.setDefault(new Locale("es","ES"));
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cuartoTextField;
    private javax.swing.JLabel cuartoTexto;
    private javax.swing.JPanel fifthPanel;
    private javax.swing.JPanel firstPanel;
    private javax.swing.JButton fourtbutton;
    private javax.swing.JPanel fourthPanel;
    private javax.swing.JButton fourthutton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField primerTextField;
    private javax.swing.JLabel primerTexto;
    private javax.swing.JTextField quintoTextField;
    private javax.swing.JLabel quintoTexto;
    private javax.swing.JPanel secondPaneñ;
    private javax.swing.JTextField segundoTextField;
    private javax.swing.JLabel segundoTexto;
    private javax.swing.JTextField tercerTextField;
    private javax.swing.JLabel tercerTexto;
    private javax.swing.JPanel thirdPanel;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables
}
