/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ramos_lopez_javierdi;

import java.applet.AudioClip;
import javax.swing.JScrollPane;

/**
 *
 * @author javie
 */
public class PlaymobilGuerrero extends javax.swing.JFrame {

    JScrollPane scrollPane;
    
    /**
     * Creates new form PlaymobilGuerrero
     */
    public PlaymobilGuerrero() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("PLAYMOBIL GUERRERO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstPanel = new javax.swing.JPanel();
        secondPanel = new javax.swing.JPanel();
        fourthPanel = new javax.swing.JPanel();
        firstLabel1 = new javax.swing.JLabel();
        secondLabel1 = new javax.swing.JLabel();
        thridPanel = new javax.swing.JPanel();
        thirdPanel1 = new javax.swing.JPanel();
        firstLabel = new javax.swing.JLabel();
        thirdPanel2 = new javax.swing.JPanel();
        fourthLabel = new javax.swing.JLabel();
        thirdLabel = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();
        fourtpanel = new javax.swing.JPanel();
        compraBoton = new javax.swing.JButton();
        fourthutton1 = new javax.swing.JButton();
        fifthButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstPanel.setBackground(new java.awt.Color(255, 255, 0));

        secondPanel.setBackground(new java.awt.Color(255, 255, 0));

        fourthPanel.setBackground(new java.awt.Color(255, 255, 0));
        secondPanel.add(fourthPanel);

        firstLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coquito.png"))); // NOI18N
        secondPanel.add(firstLabel1);

        secondLabel1.setFont(new java.awt.Font("Source Code Pro Black", 1, 48)); // NOI18N
        secondLabel1.setForeground(new java.awt.Color(0, 0, 102));
        secondLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondLabel1.setText("JUGUETERÍA TOBOGÁN");
        secondPanel.add(secondLabel1);

        thridPanel.setBackground(new java.awt.Color(255, 255, 0));

        thirdPanel1.setBackground(new java.awt.Color(255, 255, 0));

        firstLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/romanuco-removebg-preview (1) (1).png"))); // NOI18N
        thirdPanel1.add(firstLabel);

        thirdPanel2.setBackground(new java.awt.Color(255, 255, 0));
        thirdPanel2.setLayout(new java.awt.GridLayout(3, 1));

        fourthLabel.setFont(new java.awt.Font("Source Code Pro Black", 1, 48)); // NOI18N
        fourthLabel.setForeground(new java.awt.Color(0, 0, 102));
        fourthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fourthLabel.setText("Precio : 43.88€");
        thirdPanel2.add(fourthLabel);

        thirdLabel.setFont(new java.awt.Font("Source Code Pro Black", 1, 48)); // NOI18N
        thirdLabel.setForeground(new java.awt.Color(0, 0, 102));
        thirdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thirdLabel.setText("Descripción : Guerrero Persa ");
        thirdPanel2.add(thirdLabel);

        secondLabel.setFont(new java.awt.Font("Source Code Pro Black", 1, 48)); // NOI18N
        secondLabel.setForeground(new java.awt.Color(0, 0, 102));
        secondLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondLabel.setText("Nombre: Playmobil Guerrero");
        thirdPanel2.add(secondLabel);

        javax.swing.GroupLayout thridPanelLayout = new javax.swing.GroupLayout(thridPanel);
        thridPanel.setLayout(thridPanelLayout);
        thridPanelLayout.setHorizontalGroup(
            thridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thridPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thirdPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                    .addComponent(thirdPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        thridPanelLayout.setVerticalGroup(
            thridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thridPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thirdPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thirdPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fourtpanel.setBackground(new java.awt.Color(255, 255, 0));

        compraBoton.setBackground(new java.awt.Color(51, 255, 0));
        compraBoton.setFont(new java.awt.Font("Source Code Pro Black", 1, 36)); // NOI18N
        compraBoton.setForeground(new java.awt.Color(0, 0, 102));
        compraBoton.setText("COMPRAR");
        compraBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraBotonActionPerformed(evt);
            }
        });
        fourtpanel.add(compraBoton);

        fourthutton1.setBackground(new java.awt.Color(51, 255, 0));
        fourthutton1.setFont(new java.awt.Font("Source Code Pro Black", 1, 36)); // NOI18N
        fourthutton1.setForeground(new java.awt.Color(0, 0, 102));
        fourthutton1.setText("VOLVER");
        fourthutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthutton1ActionPerformed(evt);
            }
        });
        fourtpanel.add(fourthutton1);

        fifthButton.setBackground(new java.awt.Color(255, 0, 0));
        fifthButton.setFont(new java.awt.Font("Source Code Pro Black", 1, 36)); // NOI18N
        fifthButton.setForeground(new java.awt.Color(0, 0, 0));
        fifthButton.setText(org.openide.util.NbBundle.getMessage(PlaymobilGuerrero.class, "Vendido.fifthButton.text")); // NOI18N
        fifthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifthButtonActionPerformed(evt);
            }
        });
        fourtpanel.add(fifthButton);

        javax.swing.GroupLayout firstPanelLayout = new javax.swing.GroupLayout(firstPanel);
        firstPanel.setLayout(firstPanelLayout);
        firstPanelLayout.setHorizontalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(secondPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thridPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(fourtpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        firstPanelLayout.setVerticalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secondPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thridPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fourtpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que contedrá el método para volver un paso atrás en la aplicación
     * @param evt 
     */
    private void fourthutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthutton1ActionPerformed
      
        Playmobil p = new Playmobil(this,true);
        
        this.setVisible(false);
        p.setVisible(true);
    }//GEN-LAST:event_fourthutton1ActionPerformed

    private void fifthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifthButtonActionPerformed

        System.exit(0);
    }//GEN-LAST:event_fifthButtonActionPerformed

    private void compraBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraBotonActionPerformed

        Formulario f = new Formulario();
        this.setVisible(false);
        f.setVisible(true);
    }//GEN-LAST:event_compraBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaymobilGuerrero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaymobilGuerrero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaymobilGuerrero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaymobilGuerrero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaymobilGuerrero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compraBoton;
    private javax.swing.JButton fifthButton;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JLabel firstLabel1;
    private javax.swing.JPanel firstPanel;
    private javax.swing.JLabel fourthLabel;
    private javax.swing.JPanel fourthPanel;
    private javax.swing.JButton fourthutton1;
    private javax.swing.JPanel fourtpanel;
    private javax.swing.JLabel secondLabel;
    private javax.swing.JLabel secondLabel1;
    private javax.swing.JPanel secondPanel;
    private javax.swing.JLabel thirdLabel;
    private javax.swing.JPanel thirdPanel1;
    private javax.swing.JPanel thirdPanel2;
    private javax.swing.JPanel thridPanel;
    // End of variables declaration//GEN-END:variables
}
